### ISSUE TITLE
Provide the actual source code ?

### ISSUE THREAD

**Issue by gregdel** [kotc/ovhnas#1]
Hello !

You've worked on this project and it seems really interesting ! I'd like to know what your doing so I could do it myself to :)
Can you provide the source code ? You script, kernel config and everything needed to contribute ?

Thanks

**Comment by kotc** [comment]
that's the plan, i've grabbed github long time ago to have it available once i get around to tidy the code. also, trying to get some OVH interest into it

**Comment by gregdel** [comment]
Don't be shy :)
I'd love to see how you managed to get it working. I can't event test your kernel because I don't have the password to download it ;(

**Comment by kotc** [comment]
no worries, will do. and i encourage you to join #sysarm @ freenode
